#
inaccuracyMultiplier=1.25
#
arrowKnockbackMultiplier=1.0
#
arrowVelocity=0.8
#Additional knockback applied to the hit target, where 1 equals the bow having Punch I. Only whole numbers allowed.
additionalArrowKnockback=0
#
arrowDamageMultiplier=1.0
#Whether skeletons should try to retreat if the player comes closer.
shouldStrafe=false
