//it would've helped to know that I could do /kubejs inventory AFTER I did all this shit. Oh well
//KUBEJS CUSTOM ITEMS
StartupEvents.modifyCreativeTab('kubejs:tab', event => {

    event.remove('kubejs:raw_silver_bricks')

    event.remove('kubejs:fieldstone')
    event.remove('kubejs:fieldstone_stairs')
    event.remove('kubejs:fieldstone_slab')
    event.remove('kubejs:fieldstone_wall')
    event.remove('kubejs:fired_fieldstone')
    event.remove('kubejs:fired_fieldstone_stairs')
    event.remove('kubejs:fired_fieldstone_slab')
    event.remove('kubejs:fired_fieldstone_wall')
    event.remove('kubejs:fired_cobblestone')
    event.remove('kubejs:fired_cobblestone_stairs')
    event.remove('kubejs:fired_cobblestone_slab')
    event.remove('kubejs:fired_cobblestone_wall')
    event.remove('kubejs:fired_bricks')
    event.remove('kubejs:fired_bricks_stairs')
    event.remove('kubejs:fired_bricks_slab')
    event.remove('kubejs:fired_bricks_wall')
    event.remove('kubejs:mossy_fired_cobblestone')
    event.remove('kubejs:mossy_fired_cobblestone_stairs')
    event.remove('kubejs:mossy_fired_cobblestone_slab')
    event.remove('kubejs:mossy_fired_cobblestone_wall')

    event.remove('kubejs:cobbled_granite')
    event.remove('kubejs:cobbled_diorite')
    event.remove('kubejs:cobbled_andesite')
    event.remove('kubejs:cobbled_granite_stairs')
    event.remove('kubejs:cobbled_diorite_stairs')
    event.remove('kubejs:cobbled_andesite_stairs')
    event.remove('kubejs:cobbled_granite_slab')
    event.remove('kubejs:cobbled_diorite_slab')
    event.remove('kubejs:cobbled_andesite_slab')
    event.remove('kubejs:cobbled_granite_wall')
    event.remove('kubejs:cobbled_diorite_wall')
    event.remove('kubejs:cobbled_andesite_wall')

    event.remove('kubejs:fired_cobbled_granite')
    event.remove('kubejs:fired_cobbled_diorite')
    event.remove('kubejs:fired_cobbled_andesite')
    event.remove('kubejs:fired_cobbled_granite_stairs')
    event.remove('kubejs:fired_cobbled_diorite_stairs')
    event.remove('kubejs:fired_cobbled_andesite_stairs')
    event.remove('kubejs:fired_cobbled_granite_slab')
    event.remove('kubejs:fired_cobbled_diorite_slab')
    event.remove('kubejs:fired_cobbled_andesite_slab')
    event.remove('kubejs:fired_cobbled_granite_wall')
    event.remove('kubejs:fired_cobbled_diorite_wall')
    event.remove('kubejs:fired_cobbled_andesite_wall')

    event.remove('kubejs:titanium_ore')
    event.remove('kubejs:aquamarine_ore')
    event.remove('kubejs:copper_knife')
    event.remove('kubejs:opal_ore')
    event.remove('kubejs:raw_titanium')
    event.remove('kubejs:chain_mesh')
    event.remove(['kubejs:frog_leg', 'kubejs:cooked_frog_leg', 'kubejs:golden_frog_leg'])
    event.remove('#minecraft:goaway')

    event.remove('kubejs:cherry')
    event.remove('kubejs:cranberries')
    event.remove('kubejs:plum')
    event.remove('kubejs:durian')
    event.remove('kubejs:pear')
    event.remove('kubejs:mango')
    event.remove('kubejs:chestnut')

    event.remove('kubejs:cherry_crate')
    event.remove('kubejs:cranberry_crate')
    event.remove('kubejs:plum_crate')
    event.remove('kubejs:durian_crate')
    event.remove('kubejs:pear_crate')
    event.remove('kubejs:mango_crate')
    event.remove('kubejs:chestnut_crate')

    event.remove('kubejs:pearl')
    event.remove('kubejs:aquamarine')

    event.remove('kubejs:valkyrie_feather')
    event.remove('kubejs:slider_rubble')
    event.remove('kubejs:serpant_horn')

})