
[logbegone]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Unable to find animation: snake.move for Snake", "org.embeddedt.modernfix.dynamicresources.ModelMissingException", "[EMI/]", "Exception thrown when parsing EMI recipe (no ID available)", "Failed to load function miniboss_boss_bars:"]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Unable to find animation: snake.move for Snake", "org.embeddedt.modernfix.dynamicresources.ModelMissingException", "[EMI/]", "Exception thrown when parsing EMI recipe (no ID available)", "Failed to load function miniboss_boss_bars:"]

