#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jan 14 22:53:27 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=Just Colored Lighting (v0.4.4).zip
enableShaders=false
